












































name: SAP_ASSEMBLY
description: "A new Flutter project."


publish_to: "none" 













version: 1.0.0+1

environment:
  sdk: ^3.5.3







dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  audioplayers: ^6.1.0
  lottie: ^3.1.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.0
  whatsapp_unilink: ^2.1.0
  flutter_native_splash: ^2.4.3
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.1.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ico.png"
  image_path_ios: "assets/ico.png"
flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/ico.png 
  android: true
  ios: true




flutter:
  
  
  
  uses-material-design: true

  
  assets:
    - assets/
